
#docker-compose up     # start docker with logs printed to stdout
#docker-compose up -d  # start detached (daemon) to run in the background
#docker-compose down   # shutdown detached docker instances


services:

  db:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Turitopdb01
      - MYSQL_DATABASE=turitopdb
      - MYSQL_USER=turitop
      - MYSQL_PASSWORD=Turitopdb01
    expose:
      - 3306
      - 33060

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - ./wp_data:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins
    ports:
      - 8082:80
    depends_on:
      - db
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=turitop
      - WORDPRESS_DB_PASSWORD=Turitopdb01
      - WORDPRESS_DB_NAME=turitopdb

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
  
volumes:
  db_data:
  wp_data: